version: v0.10.1

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://localhost:3000/
  allowed_return_urls:
    - http://localhost:3000
    - http://localhost:3000/hydra/login

  methods:
    password:
      enabled: true
    totp:
      enabled: true
      config:
        issuer: Lauset
    lookup_secret:
      enabled: true
    # webauthn:
    #   enabled: true
    #   config:
    #     passwordless: true
    #     rp:
    #       display_name: "Lauset"
    #       id: localhost
    # oidc:
    #   enabled: true
    # config:
    #   providers:
    #   - id: upstream-oidc
    #     provider: generic
    #     label: string
    #     client_id: string
    #     client_secret: string
    #     issuer_url: string
    #     auth_url: string
    #     token_url: string

  flows:
    error:
      ui_url: http://localhost:3000/error

    settings:
      ui_url: http://localhost:3000/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://localhost:3000/recovery

    verification:
      enabled: true
      ui_url: http://localhost:3000/settings/verification
      after:
        default_browser_return_url: http://localhost:3000/

    logout:
      after:
        default_browser_return_url: http://localhost:3000/login

    login:
      ui_url: http://localhost:3000/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:3000/registration
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  # default_schema_url: file:///etc/config/kratos/identity.schema.json
  default_schema_id: person
  schemas:
    - id: person
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
