version: '3.7'

services:
  kratos-migrate:
    image: oryd/kratos:v0.8.2
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.8.2
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=debug
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - intranet
  
  hydra-migrate:
    image: oryd/hydra:v1.10.7-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/hydra
    command: migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  hydra:
    depends_on:
      - hydra-migrate
    image: oryd/hydra:v1.10.7-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
      - LOG_LEVEL=debug
      - HYDRA_URL=http://hydra:4445/
    ports:
      - '4444:4444' # public
      - '4445:4445' # admin
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/hydra
    command: -c /etc/config/hydra/hydra.yml serve all --dangerous-force-http
    restart: on-failure
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

  #  alias hydra="docker-compose exec hydra hydra"

  #    hydra clients create \
  #    --endpoint http://127.0.0.1:4445/ \
  #    --id secure-app \
  #    --secret secure-app \
  #    --grant-types client_credentials
  #    --scopes oidc,email,profile
  #    --callbacks http://localhost:4180/oauth2/callback

  #    hydra clients create \
  #    --endpoint http://127.0.0.1:4445 \
  #    --id auth-code-client \
  #    --secret secret \
  #    --grant-types authorization_code,refresh_token \
  #    --response-types code,id_token \
  #    --scope openid,offline \
  #    --callbacks http://127.0.0.1:5555/callback

  secure-app:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - 4180:4180
    volumes:
      - type: bind
        source: ./www
        target: /www
    # https://hydra:4444/.well-known/openid-configuration
    #   --login-url http://localhost:4444/oauth2/auth
    #   --oidc-jwks-url http://localhost:4444/.well-known/jwks.json
    #   --profile-url http://localhost:4444/userinfo
    #   --redeem-url http://localhost:4444/oauth2/token
    command: |
      --upstream=file:///www/static#/
      --client-id=secure-app
      --client-secret=secure-app
      --cookie-secret=VOT5eQoY4rdUcXFqnyKk_fcBfTbSFZ0Z_WsVbNa4oyw=
      --email-domain=*
      --oidc-issuer-url=http://localhost:4444/
      --redirect-url=http://localhost:4180/oauth2/callback
      --prompt=consent
      --provider=oidc
    restart: on-failure
    network_mode: host

networks:
  intranet:

volumes:
  kratos-sqlite:
  hydra-sqlite:
