version: "3.7"

services:
  kratos-migrate:
    image: oryd/kratos:v0.10.1
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: migrate sql -e --yes

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.10.1
    # build:
    #   context: ./kratos
    #   dockerfile: ./.docker/Dockerfile-build
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - KRATOS_ADMIN_URL=http://localhost:4434
      # - LOG_LEVEL=debug
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos

  hydra-migrate:
    image: oryd/hydra:v2.0.1
    # build:
    #   context: ./hydra
    #   dockerfile: ./.docker/Dockerfile-build
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/hydra
    command: migrate sql -e --yes
    restart: on-failure

  hydra:
    depends_on:
      - hydra-migrate
    image: oryd/hydra:v2.0.1
    # build:
    #   context: ./hydra
    #   dockerfile: ./.docker/Dockerfile-build
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
      - HYDRA_URL=http://localhost:4445/
      - ORY_SDK_URL=http://localhost:4445/
      # - LOG_LEVEL=debug
    ports:
      - "4444:4444" # public
      - "4445:4445" # admin
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/hydra
    command: -c /etc/config/hydra/hydra.yml serve all --dev
    restart: on-failure

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"

  #  alias hydra="docker-compose exec hydra hydra"

  # hydra create client \
  #    --name secure-app \
  #    --grant-type authorization_code \
  #    --scope openid,email,profile \
  #    --token-endpoint-auth-method client_secret_post \
  #    --redirect-uri http://localhost:4180/oauth2/callback

  secure-app:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - "4180:4180"
    volumes:
      - type: bind
        source: ./www
        target: /www
    # https://hydra:4444/.well-known/openid-configuration
    #   --skip-oidc-discovery
    #   --oidc-issuer-url=http://hydra:4444/
    #   --login-url http://localhost:4444/oauth2/auth
    #   --oidc-jwks-url http://hydra:4444/.well-known/jwks.json
    #   --profile-url http://hydra:4444/userinfo
    #   --redeem-url http://hydra:4444/oauth2/token
    command: |
      --http-address=0.0.0.0:4180
      --upstream=file:///www/static#/
      --client-id=0980f1aa-a23e-443c-b121-77a583a19f7d
      --client-secret=uRckz8W91L0pLtbvddYN8ogCyr
      --cookie-secret=VOT5eQoY4rdUcXFqnyKk_fcBfTbSFZ0Z_WsVbNa4oyw=
      --email-domain=*
      --redirect-url=http://localhost:4180/oauth2/callback
      --skip-oidc-discovery
      --oidc-issuer-url=http://hydra:4444/
      --login-url http://localhost:4444/oauth2/auth
      --oidc-jwks-url http://hydra:4444/.well-known/jwks.json
      --profile-url http://hydra:4444/userinfo
      --redeem-url http://hydra:4444/oauth2/token
      --prompt=consent
      --provider=oidc
    restart: on-failure

volumes:
  kratos-sqlite:
  hydra-sqlite:
