name: Create and publish Docker image

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VERSION: ${{ github.sha }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.VERSION }}
            latest
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Checkout homelab repository
        uses: actions/checkout@v2
        with:
          repository: addreas/homelab
          path: homelab
          token: ${{ secrets.PUSH_SECRET }}

      - name: Generate version file
        run: |
          cat <<EOF > ./homelab/resources/system/lauset/version.cue
          package kube

          lausetVersion: "$VERSION"
          EOF
      - name: Upgrade staging environment by pushing to homelab
        env:
          REPO_KEY: ${{ secrets.PUSH_SECRET }}
          USERNAME: github-actions[bot]
        run: |
          cd homelab
          git config --local user.name "github-actions[bot]"
          git config --local user.email "jonas+bot@jdahl.se"
          git add resources/system/lauset/version.cue
          git commit -m "Upgrade lauset version to $VERSION"
          git push https://$USERNAME:$REPO_KEY@github.com/addreas/homelab.git
